version: "3.9"

services:
  frontend:
    image: node:alpine
    command: sh -c "cd /app && npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
